name: Run Colab Notebook Automatically

on:
  schedule:
    - cron: '30 7 * * 1-5' # 平日の日本時間 16:30 (UTC 7:30)
  workflow_dispatch: # 手動でも動かせるようにするボタン

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # ★ここを追加：PythonをJupyterのカーネルとして登録する
          python -m ipykernel install --user --name python3

      - name: Execute Jupyter Notebook
        run: |
          papermill J_Quants_API.ipynb output_notebook.ipynb
